# Generated by Django 5.1.3 on 2024-11-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
